### ISSUE TITLE
A bonafide issue before you even post the source code.

### ISSUE THREAD

**Issue by cameron-elliott** [Intel-Media-SDK/dispatcher#1]
In the file: opensource/mfx_dispatch/CMakeLists.txt

The following lines appear:

```
    set( link_flags_list "-Wl,--no-undefined,-z,relro,-z,now,-z,noexecstack,-ldl")
    append_property( ${target} LINK_FLAGS "${link_flags_list} -fstack-protector" )
```

But those options get output on Windows platforms, which is incorrect because they are Gcc options.
I propose the following replacement:

```
  if( ${CMAKE_SYSTEM_NAME} MATCHES Linux )
    set( link_flags_list "-Wl,--no-undefined,-z,relro,-z,now,-z,noexecstack,-ldl")
    append_property( ${target} LINK_FLAGS "${link_flags_list} -fstack-protector" )
  endif()
```

This has been tested locally.

I would be happy to submit a pull request if someone from Intel posts the actual dispatcher.

**Comment by onabiull** [comment]
With current split dispatcher between windows/linux I believe this issue not actual anymore. Going forward https://github.com/Intel-Media-SDK/MediaSDK/ are correct home for Media SDK, Dispatcher and Samples.
